/* tslint:disable */
/* eslint-disable */
/**
 * Achaia.Wiskey.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Bottle,
} from '../models/index';
import {
    BottleFromJSON,
    BottleToJSON,
} from '../models/index';

/**
 * 
 */
export class InventoryApi extends runtime.BaseAPI {

    /**
     */
    async getAllBottlesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Bottle>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Inventory`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BottleFromJSON));
    }

    /**
     */
    async getAllBottles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Bottle>> {
        const response = await this.getAllBottlesRaw(initOverrides);
        return await response.value();
    }

}
