/* tslint:disable */
/* eslint-disable */
/**
 * Achaia.Wiskey.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Distillery
 */
export interface Distillery {
    /**
     * 
     * @type {number}
     * @memberof Distillery
     */
    distilleryId?: number;
    /**
     * 
     * @type {string}
     * @memberof Distillery
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Distillery
     */
    stateProvince?: string;
}

/**
 * Check if a given object implements the Distillery interface.
 */
export function instanceOfDistillery(value: object): value is Distillery {
    return true;
}

export function DistilleryFromJSON(json: any): Distillery {
    return DistilleryFromJSONTyped(json, false);
}

export function DistilleryFromJSONTyped(json: any, ignoreDiscriminator: boolean): Distillery {
    if (json == null) {
        return json;
    }
    return {
        
        'distilleryId': json['distilleryId'] == null ? undefined : json['distilleryId'],
        'name': json['name'] == null ? undefined : json['name'],
        'stateProvince': json['stateProvince'] == null ? undefined : json['stateProvince'],
    };
}

export function DistilleryToJSON(value?: Distillery | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'distilleryId': value['distilleryId'],
        'name': value['name'],
        'stateProvince': value['stateProvince'],
    };
}

