/* tslint:disable */
/* eslint-disable */
/**
 * Achaia.Wiskey.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReleaseType
 */
export interface ReleaseType {
    /**
     * 
     * @type {number}
     * @memberof ReleaseType
     */
    releaseTypeId?: number;
    /**
     * 
     * @type {string}
     * @memberof ReleaseType
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ReleaseType
     */
    code?: string;
}

/**
 * Check if a given object implements the ReleaseType interface.
 */
export function instanceOfReleaseType(value: object): value is ReleaseType {
    return true;
}

export function ReleaseTypeFromJSON(json: any): ReleaseType {
    return ReleaseTypeFromJSONTyped(json, false);
}

export function ReleaseTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReleaseType {
    if (json == null) {
        return json;
    }
    return {
        
        'releaseTypeId': json['releaseTypeId'] == null ? undefined : json['releaseTypeId'],
        'name': json['name'] == null ? undefined : json['name'],
        'code': json['code'] == null ? undefined : json['code'],
    };
}

export function ReleaseTypeToJSON(value?: ReleaseType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'releaseTypeId': value['releaseTypeId'],
        'name': value['name'],
        'code': value['code'],
    };
}

